"""Render the reviewed old-host Nginx config from public one-to-one routes."""
import argparse
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'deploy-legacy/tio2-production-adoption.conf'


def public_paths():
    with (ROOT / 'planning/SITE_MAP.csv').open(encoding='utf-8-sig', newline='') as source:
        rows = list(csv.DictReader(source))
    # The receipt page is session-specific; it must be mapped separately.
    paths = [row['url'] for row in rows if row['url'].startswith('/') and row['url'] != '/thank-you/']
    if len(paths) != 57 or len(paths) != len(set(paths)):
        raise SystemExit('The 57 reviewed public paths changed; re-audit both site sitemaps before regenerating.')
    return paths


def render(paths):
    mappings = '\n'.join('    ' + path + ' 1;' for path in paths)
    return f'''# Generated by scripts/build-legacy-domain-redirect.py.
# Apply only on the legacy Nginx host after verifying both public sitemaps.
# Unmatched paths retain the old upstream for separate mapping review.
map_hash_bucket_size 128;
map $uri $tio2_has_new_equivalent {{
    default 0;
{mappings}
}}

server {{
    listen 80;
    listen [::]:80;
    server_name tio2malaysia.com www.tio2malaysia.com;
    location ^~ /.well-known/acme-challenge/ {{ root /var/www/tio2-acme; }}
    location = /sitemap.xml {{ return 301 https://tio2products.com/wp-sitemap.xml; }}
    location = /robots.txt {{
        default_type text/plain;
        return 200 "User-agent: *\\nAllow: /\\nSitemap: https://tio2products.com/wp-sitemap.xml\\n";
    }}
    location / {{
        if ($tio2_has_new_equivalent) {{ return 301 https://tio2products.com$request_uri; }}
        return 301 https://tio2malaysia.com$request_uri;
    }}
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name tio2malaysia.com www.tio2malaysia.com;
    ssl_certificate /etc/letsencrypt/live/tio2malaysia.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tio2malaysia.com/privkey.pem;
    if ($tio2_has_new_equivalent) {{ return 301 https://tio2products.com$request_uri; }}
    if ($host = www.tio2malaysia.com) {{ return 301 https://tio2malaysia.com$request_uri; }}
    location = /sitemap.xml {{ return 301 https://tio2products.com/wp-sitemap.xml; }}
    location = /robots.txt {{
        default_type text/plain;
        return 200 "User-agent: *\\nAllow: /\\nSitemap: https://tio2products.com/wp-sitemap.xml\\n";
    }}
    location / {{
        # Preserve the old upstream for paths without a verified replacement.
        if (-f /etc/tio2-production/cms-maintenance.json) {{ return 503; }}
        include /etc/tio2-production/web-upstream.conf;
        proxy_set_header Host tio2malaysia.com;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }}
}}

server {{
    listen 127.0.0.1:8081;
    server_name tio2malaysia.com www.tio2malaysia.com;
    location / {{ include /etc/tio2-production/web-upstream.conf; proxy_set_header Host tio2malaysia.com; }}
}}
'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='verify the committed config matches the reviewed route map')
    args = parser.parse_args()
    expected = render(public_paths())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding='utf-8') != expected:
            raise SystemExit('Legacy Nginx config differs from the reviewed public route map.')
        print('PASS: legacy Nginx config has the 57 reviewed one-to-one paths')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding='utf-8')
