<?php $ga4_id = tio2_ga4_measurement_id(); $malay_policy = function_exists('tio2_utility_id') && tio2_utility_id() === 'LEGAL-PRIV-MS'; ?>
<footer class="footer"><div class="wrap footerGrid"><div><img class="logo" src="<?php echo esc_url(get_template_directory_uri().'/assets/logo-reverse.svg'); ?>" alt="TiO2 Malaysia" width="180" height="60"><p>TiO2Products: titanium dioxide products, technical information and sourcing support for industrial buyers worldwide.</p></div><nav aria-label="Footer navigation"><?php if(has_nav_menu('footer'))wp_nav_menu(['theme_location'=>'footer','container'=>false,'depth'=>1]);else tio2_navigation(); ?></nav><nav class="footerUtilities" aria-label="Contact and policies"><a href="<?php echo esc_url(home_url('/contact/')); ?>">Contact</a><a href="<?php echo esc_url(home_url('/privacy-policy/')); ?>">Privacy Policy</a><a href="<?php echo esc_url(home_url('/cookie-policy/')); ?>">Cookie Policy</a><button type="button" class="cookie-settings-open"><?php echo $malay_policy ? 'Tetapan Kuki' : 'Cookie Settings'; ?></button></nav><a class="button primary" href="<?php echo esc_url(home_url('/request-a-quote/')); ?>">RFQ</a></div></footer>
<?php if ($ga4_id): ?>
<aside id="analytics-consent" class="analytics-consent" data-ga4-id="<?php echo esc_attr($ga4_id); ?>" aria-label="<?php echo $malay_policy ? 'Pilihan analitik' : 'Analytics choice'; ?>" hidden>
  <p><?php echo $malay_policy ? 'Kami menggunakan Google Analytics 4 hanya selepas anda bersetuju. Kuki yang diperlukan tetap berfungsi.' : 'We use Google Analytics 4 only if you agree. Necessary cookies remain available.'; ?> <a href="<?php echo esc_url(home_url('/cookie-policy/')); ?>"><?php echo $malay_policy ? 'Cookie Policy (English)' : 'Cookie Policy'; ?></a></p>
  <div class="analytics-consent-actions"><button type="button" class="analytics-allow"><?php echo $malay_policy ? 'Benarkan analitik' : 'Allow analytics'; ?></button><button type="button" class="analytics-reject"><?php echo $malay_policy ? 'Tolak analitik' : 'Reject analytics'; ?></button></div>
</aside>
<?php endif; ?>
<dialog id="cookie-settings" aria-labelledby="cookie-settings-title"><h2 id="cookie-settings-title"><?php echo $malay_policy ? 'Tetapan Kuki' : 'Cookie settings'; ?></h2>
<?php if ($ga4_id): ?>
<p><?php echo $malay_policy ? 'Storan yang diperlukan menyokong pengesahan borang dan pentadbiran laman. Google Analytics 4 hanya digunakan jika anda membenarkannya.' : 'Necessary browser storage supports form confirmation and site administration. Google Analytics 4 is used only if you allow it.'; ?></p>
<p id="analytics-status" role="status"></p><div class="cookie-dialog-actions"><button type="button" class="analytics-enable"><?php echo $malay_policy ? 'Benarkan analitik' : 'Allow analytics'; ?></button><button type="button" class="analytics-disable"><?php echo $malay_policy ? 'Matikan analitik' : 'Disable analytics'; ?></button></div>
<?php else: ?>
<p>No optional Analytics or advertising technology is currently active on this site. Necessary browser storage supports form confirmation and site administration where applicable.</p>
<?php endif; ?>
<div class="cookie-dialog-actions"><button type="button" class="cookie-settings-close"><?php echo $malay_policy ? 'Tutup' : 'Close'; ?></button><a href="<?php echo esc_url(home_url('/cookie-policy/')); ?>"><?php echo $malay_policy ? 'Baca Cookie Policy (English)' : 'Read Cookie Policy'; ?></a></div></dialog>
<?php wp_footer(); ?></body></html>
