<?php
get_header(); the_post(); $d=function_exists('tio2_product_data')?tio2_product_data(get_the_ID()):[];
if(!$d){echo '<main id="main" class="wrap section"><h1>'.esc_html(get_the_title()).'</h1></main>';get_footer();return;}
?>
<main id="main">
<nav class="wrap crumb" aria-label="Breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><span aria-hidden="true">/</span><a href="<?php echo esc_url(get_post_type_archive_link('product')); ?>">Products</a><span aria-hidden="true">/</span><span aria-current="page"><?php the_title(); ?></span></nav>
<section class="hero"><div class="wrap heroGrid"><div><p class="eyebrow"><?php echo esc_html($d['category'].(has_term($d['process_key'],'product_process',get_the_ID())?' · '.$d['process_label']:'')); ?></p><h1><?php echo esc_html($d['h1']); ?></h1><p class="lead"><?php echo esc_html(get_the_excerpt()); ?></p><?php tio2_paragraphs($d['hero_paragraphs']); ?>
<?php if(tio2_target_url('quote')||tio2_target_url('sample')): ?><div class="actions"><?php tio2_action('quote',$d['quote_label'],true);tio2_action('sample',$d['sample_label']); ?></div><?php endif; ?></div>
<aside class="dataVisual"><span class="gradeBadge"><?php the_title(); ?></span><h2><?php echo esc_html($d['summary_title']); ?></h2><ul><?php foreach($d['summary'] as $item)echo '<li>'.esc_html($item).'</li>'; ?></ul></aside></div></section>
<section class="section"><div class="wrap"><h2><?php echo esc_html($d['positioning_title']); ?></h2><?php tio2_paragraphs($d['positioning_paragraphs'],'sectionIntro'); ?><div class="facts"><?php foreach($d['facts'] as $fact)echo '<div class="fact">'.esc_html($fact).'</div>'; ?></div><?php if(has_term($d['process_key'],'product_process',get_the_ID()) && ($url=tio2_target_url($d['process_key'])))echo '<a class="processLink" href="'.esc_url($url).'">'.esc_html($d['process_link_label']).'</a>'; ?></div></section>
<section class="section band"><div class="wrap"><h2><?php echo esc_html($d['applications_title']); ?></h2><?php if(!empty($d['applications_intro']))tio2_paragraphs([$d['applications_intro']]); ?><div class="appGrid"><?php foreach(tio2_public_applications(get_the_ID()) as $app): ?><article class="card <?php echo !empty($app['qualified'])?'paper':''; ?>"><h3><?php echo esc_html($app['title']); ?></h3><p><?php echo esc_html($app['text']); ?></p></article><?php endforeach; ?></div>
<?php $links='';$active=array_column(tio2_public_applications(get_the_ID()),'relation');foreach($d['application_links'] as $link){$key=$link['relation'];if(!in_array($key,$active,true))continue;if($url=tio2_target_url($key))$links.='<a href="'.esc_url($url).'">'.esc_html($link['label']).'</a>';}if($links)echo '<div class="topicLinks">'.$links.'</div>'; ?></div></section>
<section class="section"><div class="wrap"><h2><?php echo esc_html($d['evaluation_title']); ?></h2><?php if(!empty($d['evaluation_intro']))tio2_paragraphs([$d['evaluation_intro']]); ?><div class="evalGrid"><?php foreach($d['evaluation'] as $group): ?><article class="eval"><h3><?php echo esc_html($group['title']); ?></h3><ul><?php foreach($group['items'] as $item)echo '<li>'.esc_html($item).'</li>'; ?></ul></article><?php endforeach; ?></div><p class="note"><?php echo esc_html($d['evaluation_note']); ?></p></div></section>
<section class="section band"><div class="wrap"><h2><?php echo esc_html($d['technical_title']); ?></h2><?php if(!empty($d['technical_intro']))tio2_paragraphs([$d['technical_intro']]); ?><div class="tableWrap"><table class="techTable"><caption class="screen-reader-text"><?php echo esc_html($d['technical_title']); ?></caption><thead><tr><?php foreach(tio2_table_columns($d) as $col)echo '<th scope="col">'.esc_html($col['label']).'</th>'; ?></tr></thead><tbody><?php foreach(tio2_public_rows(get_the_ID()) as $row): ?><tr><?php foreach(tio2_table_columns($d) as $i=>$col): ?><?php if($i===0): ?><th scope="row"><?php echo esc_html($row[$col['key']]); ?></th><?php else: ?><td><span class="mobileLabel" aria-hidden="true"><?php echo esc_html($col['label']); ?></span><?php echo esc_html($row[$col['key']]??'—'); ?></td><?php endif; ?><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><p class="note"><?php echo esc_html($d['technical_note']); ?></p><?php tio2_action('documents',$d['tds_label'],false,['requested_type'=>'TDS']); ?></div></section>
<?php if(tio2_target_url('documents')): ?><section class="documentBand"><div class="wrap documentGrid"><div><h2><?php echo esc_html($d['documents_title']); ?></h2><?php tio2_paragraphs(array_slice($d['documents_paragraphs'],0,1));tio2_action('documents',$d['documents_label']); ?><p class="small"><?php echo esc_html(implode(' ',array_slice($d['documents_paragraphs'],1)));  ?></p></div><div class="docOptions"><?php foreach($d['documents_options'] as $item)echo '<p class="docOption">'.esc_html($item).'</p>'; ?></div></div></section><?php endif; ?>
<section class="section"><div class="wrap"><h2><?php echo esc_html($d['markets_title']); ?></h2><?php tio2_paragraphs(array_slice($d['markets_paragraphs'],0,1));$links='';foreach($d['market_links'] as $link)if($url=tio2_target_url($link['relation']))$links.='<a class="market" href="'.esc_url($url).'">'.esc_html($link['label']).'</a>';if($links)echo '<div class="marketGrid">'.$links.'</div>';tio2_paragraphs(array_slice($d['markets_paragraphs'],1),'small'); ?></div></section>
<?php if(tio2_target_url('sample')): ?><section class="section band"><div class="wrap"><h2><?php echo esc_html($d['sample_title']); ?></h2><?php tio2_paragraphs(array_slice($d['sample_paragraphs'],0,1));tio2_action('sample',$d['sample_label'],true);tio2_paragraphs(array_slice($d['sample_paragraphs'],1),'small'); ?></div></section><?php endif; ?>
</main><?php get_footer(); ?>
